"""Dashboard dropdown options and form defaults."""

CITIES = [
    "adelboden",
    "aigle",
    "altdorf",
    "basel_binningen",
    "bern",
    "buchs_aarau",
    "bullet_la_fretaz",
    "chur",
    "col_du_grand_st_bernard",
    "davos",
    "disentis",
    "engelberg",
    "geneva",
    "glarus",
    "guttingen",
    "interlaken",
    "la_chaux_de_fonds",
    "lausanne_pully",
    "locarno_magadino",
    "locarno_monti",
    "lugano",
    "luzern",
    "montana",
    "neuchatel",
    "payerne",
    "piotta_ambri",
    "poschiavo_robbia",
    "runenberg",
    "san_bernardino",
    "schaffhausen",
    "scuol",
    "sion",
    "st_gallen",
    "st_moritz_samedam",
    "ulrichen",
    "vaduz",
    "wynau",
    "zermatt",
    "zurich_fluntern",
    "zurich_kloten",
]
BUILDING_TYPES = ["mfh", "sfh", "office"]
DEMAND_TYPES = ["heating", "cooling", "electricity", "dhw"]

DEFAULTS = {
    "length": 11.0,
    "width": 14.0,
    "floor_height": 3.5,
    "number_of_floors": 4,
    "construction_year": 2014,
    "north_angle": 90.0,
    "nwwr": 0.75,
    "ewwr": 0.15,
    "swwr": 0.3,
    "wwwr": 0.3,
    "u_ground": 0.227,
    "u_wall": 0.153,
    "u_roof": 0.176,
    "u_window": 1.176,
}
